### PR TITLE
Replicate a simple version FLAN dataset

### PR DESCRIPTION
**Pull request by uSaiPrashanth**
Created `prepare_datasets.py` to save all datasets in a json file to be utilized for finetuning and evaluation purposes

### CODE REVIEW

**Comment by Zcchill** [comment]
When I run the “prepare_datasets.py”, I came across a bug showed below (I have install all the packages according to the requirements.txt):
` python prepare_datasets.py 
['aeslc_10templates', 'ag_news_subset_10templates', 'anli_r1_10templates', 'anli_r2_10templates', 'anli_r3_10templates', 'arc_challenge_10templates', 'arc_easy_10templates', 'cnn_dailymail_10templates', 'cola_10templates', 'common_gen_10templates', 'coqa_10templates', 'cosmos_qa_10templates', 'definite_pronoun_resolution_10templates', 'e2e_nlg_10templates', 'fix_punct_10templates', 'gigaword_10templates', 'glue_mrpc_10templates', 'glue_qqp_10templates', 'hellaswag_10templates', 'imdb_reviews_10templates', 'math_dataset_10templates', 'mnli_matched_10templates', 'mnli_mismatched_10templates', 'natural_questions_10templates', 'newsroom_10templates', 'openbookqa_10templates', 'opinion_abstracts_idebate_10templates', 'opinion_abstracts_rotten_tomatoes_10templates', 'para_crawl_enes_10templates', 'paws_wiki_10templates', 'piqa_10templates', 'qnli_10templates', 'quac_10templates', 'samsum_10templates', 'sentiment140_10templates', 'snli_10templates', 'squad_v1_10templates', 'squad_v2_10templates', 'sst2_10templates', 'story_cloze_10templates', 'trec_10templates', 'trivia_qa_10templates', 'true_case_10templates', 'web_nlg_en_10templates', 'wiki_lingua_english_en_10templates', 'winogrande_10templates', 'wmt14_enfr_10templates', 'wmt16_translate_csen_10templates', 'wmt16_translate_deen_10templates', 'wmt16_translate_fien_10templates', 'wmt16_translate_roen_10templates', 'wmt16_translate_ruen_10templates', 'wmt16_translate_tren_10templates', 'wnli_10templates', 'xsum_10templates', 'bool_q_10templates', 'cb_10templates', 'copa_10templates', 'multirc_10templates', 'record_10templates', 'rte_10templates', 'wic_10templates', 'wsc_10templates']
2022-07-07 11:35:05.479945: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "Not found: Could not locate the credentials file.". Retrieving token from GCE failed with "Failed precondition: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata".
2022-07-07 11:35:05.479946: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "Not found: Could not locate the credentials file.". Retrieving token from GCE failed with "Failed precondition: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata".
2022-07-07 11:35:05.480022: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "Not found: Could not locate the credentials file.". Retrieving token from GCE failed with "Failed precondition: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata".
2022-07-07 11:35:05.480040: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "Not found: Could not locate the credentials file.". Retrieving token from GCE failed with "Failed precondition: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata".
2022-07-07 11:35:05.480046: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "Not found: Could not locate the credentials file.". Retrieving token from GCE failed with "Failed precondition: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata".`
I find that it was caused by this code:
`dataset = seqio.get_mixture_or_task(task).get_dataset(
        sequence_length={'inputs':4096,'targets':4096} # Extranous length to capture all data
)`

I have tried to reduced the version of this package as the guideline in the web, howereve, I will come across another bug:
`"""
Traceback (most recent call last):
  File "/data/users/zhouzhanchao/.miniconda/envs/iopt/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/data/users/zhouzhanchao/.miniconda/envs/iopt/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "prepare_datasets.py", line 32, in prepare_task
    dataset = seqio.get_mixture_or_task(task).get_dataset(
  File "/data/users/zhouzhanchao/.miniconda/envs/iopt/lib/python3.8/site-packages/seqio/dataset_providers.py", line 1041, in get_dataset
    ds = source.get_dataset(split=split, shuffle=shuffle, seed=seed)
  File "/data/users/zhouzhanchao/.miniconda/envs/iopt/lib/python3.8/site-packages/seqio/dataset_providers.py", line 371, in get_dataset
    return self.tfds_dataset.load(
  File "/data/users/zhouzhanchao/.miniconda/envs/iopt/lib/python3.8/site-packages/seqio/utils.py", line 137, in load
    read_config=tfds.ReadConfig(
  File "/data/users/zhouzhanchao/.miniconda/envs/iopt/lib/python3.8/site-packages/tensorflow_datasets/core/utils/read_config.py", line 112, in __init__
    super(ReadConfig, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'skip_prefetch'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "prepare_datasets.py", line 60, in <module>
    p.map(prepare_task,all_tasks)
  File "/data/users/zhouzhanchao/.miniconda/envs/iopt/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/data/users/zhouzhanchao/.miniconda/envs/iopt/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: __init__() got an unexpected keyword argument 'skip_prefetch'`

Please can you tell me my problem and how to fix it?

**Comment by Zcchill** [comment]
When I run the “prepare_datasets.py”, I came across a bug showed below (I have install all the packages according to the requirements.txt):
python prepare_datasets.py ['aeslc_10templates', 'ag_news_subset_10templates', 'anli_r1_10templates', 'anli_r2_10templates', 'anli_r3_10templates', 'arc_challenge_10templates', 'arc_easy_10templates', 'cnn_dailymail_10templates', 'cola_10templates', 'common_gen_10templates', 'coqa_10templates', 'cosmos_qa_10templates', 'definite_pronoun_resolution_10templates', 'e2e_nlg_10templates', 'fix_punct_10templates', 'gigaword_10templates', 'glue_mrpc_10templates', 'glue_qqp_10templates', 'hellaswag_10templates', 'imdb_reviews_10templates', 'math_dataset_10templates', 'mnli_matched_10templates', 'mnli_mismatched_10templates', 'natural_questions_10templates', 'newsroom_10templates', 'openbookqa_10templates', 'opinion_abstracts_idebate_10templates', 'opinion_abstracts_rotten_tomatoes_10templates', 'para_crawl_enes_10templates', 'paws_wiki_10templates', 'piqa_10templates', 'qnli_10templates', 'quac_10templates', 'samsum_10templates', 'sentiment140_10templates', 'snli_10templates', 'squad_v1_10templates', 'squad_v2_10templates', 'sst2_10templates', 'story_cloze_10templates', 'trec_10templates', 'trivia_qa_10templates', 'true_case_10templates', 'web_nlg_en_10templates', 'wiki_lingua_english_en_10templates', 'winogrande_10templates', 'wmt14_enfr_10templates', 'wmt16_translate_csen_10templates', 'wmt16_translate_deen_10templates', 'wmt16_translate_fien_10templates', 'wmt16_translate_roen_10templates', 'wmt16_translate_ruen_10templates', 'wmt16_translate_tren_10templates', 'wnli_10templates', 'xsum_10templates', 'bool_q_10templates', 'cb_10templates', 'copa_10templates', 'multirc_10templates', 'record_10templates', 'rte_10templates', 'wic_10templates', 'wsc_10templates'] 2022-07-07 11:35:05.479945: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "Not found: Could not locate the credentials file.". Retrieving token from GCE failed with "Failed precondition: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata". 2022-07-07 11:35:05.479946: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "Not found: Could not locate the credentials file.". Retrieving token from GCE failed with "Failed precondition: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata". 2022-07-07 11:35:05.480022: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "Not found: Could not locate the credentials file.". Retrieving token from GCE failed with "Failed precondition: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata". 2022-07-07 11:35:05.480040: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "Not found: Could not locate the credentials file.". Retrieving token from GCE failed with "Failed precondition: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata". 2022-07-07 11:35:05.480046: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "Not found: Could not locate the credentials file.". Retrieving token from GCE failed with "Failed precondition: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata".
I find that it was caused by this code:
dataset = seqio.get_mixture_or_task(task).get_dataset( sequence_length={'inputs':4096,'targets':4096} # Extranous length to capture all data )

I have tried to reduced the version of the package "tensorflow-datasets" as the guideline in the web, howereve, I will come across another bug:
`
Traceback (most recent call last):
File "/data/users/zhouzhanchao/.miniconda/envs/iopt/lib/python3.8/multiprocessing/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
File "/data/users/zhouzhanchao/.miniconda/envs/iopt/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
return list(map(*args))
File "prepare_datasets.py", line 32, in prepare_task
dataset = seqio.get_mixture_or_task(task).get_dataset(
File "/data/users/zhouzhanchao/.miniconda/envs/iopt/lib/python3.8/site-packages/seqio/dataset_providers.py", line 1041, in get_dataset
ds = source.get_dataset(split=split, shuffle=shuffle, seed=seed)
File "/data/users/zhouzhanchao/.miniconda/envs/iopt/lib/python3.8/site-packages/seqio/dataset_providers.py", line 371, in get_dataset
return self.tfds_dataset.load(
File "/data/users/zhouzhanchao/.miniconda/envs/iopt/lib/python3.8/site-packages/seqio/utils.py", line 137, in load
read_config=tfds.ReadConfig(
File "/data/users/zhouzhanchao/.miniconda/envs/iopt/lib/python3.8/site-packages/tensorflow_datasets/core/utils/read_config.py", line 112, in init
super(ReadConfig, self).init(**kwargs)
TypeError: init() got an unexpected keyword argument 'skip_prefetch'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "prepare_datasets.py", line 60, in
p.map(prepare_task,all_tasks)
File "/data/users/zhouzhanchao/.miniconda/envs/iopt/lib/python3.8/multiprocessing/pool.py", line 364, in map
return self._map_async(func, iterable, mapstar, chunksize).get()
File "/data/users/zhouzhanchao/.miniconda/envs/iopt/lib/python3.8/multiprocessing/pool.py", line 771, in get
raise self._value
TypeError: init() got an unexpected keyword argument 'skip_prefetch'`
`
Please can you tell me my problem and how to fix it?

**Comment by Zcchill** [comment]
When I run the “prepare_datasets.py”, I came across a bug showed below (I have install all the packages according to the requirements.txt):
`python prepare_datasets.py ['aeslc_10templates', 'ag_news_subset_10templates', 'anli_r1_10templates', 'anli_r2_10templates', 'anli_r3_10templates', 'arc_challenge_10templates', 'arc_easy_10templates', 'cnn_dailymail_10templates', 'cola_10templates', 'common_gen_10templates', 'coqa_10templates', 'cosmos_qa_10templates', 'definite_pronoun_resolution_10templates', 'e2e_nlg_10templates', 'fix_punct_10templates', 'gigaword_10templates', 'glue_mrpc_10templates', 'glue_qqp_10templates', 'hellaswag_10templates', 'imdb_reviews_10templates', 'math_dataset_10templates', 'mnli_matched_10templates', 'mnli_mismatched_10templates', 'natural_questions_10templates', 'newsroom_10templates', 'openbookqa_10templates', 'opinion_abstracts_idebate_10templates', 'opinion_abstracts_rotten_tomatoes_10templates', 'para_crawl_enes_10templates', 'paws_wiki_10templates', 'piqa_10templates', 'qnli_10templates', 'quac_10templates', 'samsum_10templates', 'sentiment140_10templates', 'snli_10templates', 'squad_v1_10templates', 'squad_v2_10templates', 'sst2_10templates', 'story_cloze_10templates', 'trec_10templates', 'trivia_qa_10templates', 'true_case_10templates', 'web_nlg_en_10templates', 'wiki_lingua_english_en_10templates', 'winogrande_10templates', 'wmt14_enfr_10templates', 'wmt16_translate_csen_10templates', 'wmt16_translate_deen_10templates', 'wmt16_translate_fien_10templates', 'wmt16_translate_roen_10templates', 'wmt16_translate_ruen_10templates', 'wmt16_translate_tren_10templates', 'wnli_10templates', 'xsum_10templates', 'bool_q_10templates', 'cb_10templates', 'copa_10templates', 'multirc_10templates', 'record_10templates', 'rte_10templates', 'wic_10templates', 'wsc_10templates'] 2022-07-07 11:35:05.479945: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "Not found: Could not locate the credentials file.". Retrieving token from GCE failed with "Failed precondition: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata". 2022-07-07 11:35:05.479946: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "Not found: Could not locate the credentials file.". Retrieving token from GCE failed with "Failed precondition: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata". 2022-07-07 11:35:05.480022: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "Not found: Could not locate the credentials file.". Retrieving token from GCE failed with "Failed precondition: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata". 2022-07-07 11:35:05.480040: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "Not found: Could not locate the credentials file.". Retrieving token from GCE failed with "Failed precondition: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata". 2022-07-07 11:35:05.480046: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "Not found: Could not locate the credentials file.". Retrieving token from GCE failed with "Failed precondition: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata".`

I find that it was caused by this code:
dataset = seqio.get_mixture_or_task(task).get_dataset( sequence_length={'inputs':4096,'targets':4096} # Extranous length to capture all data )

I have tried to reduced the version of the package "tensorflow-datasets" as the guideline in the web, howereve, I will come across another bug:
`Traceback (most recent call last):
File "/data/users/zhouzhanchao/.miniconda/envs/iopt/lib/python3.8/multiprocessing/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
File "/data/users/zhouzhanchao/.miniconda/envs/iopt/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
return list(map(*args))
File "prepare_datasets.py", line 32, in prepare_task
dataset = seqio.get_mixture_or_task(task).get_dataset(
File "/data/users/zhouzhanchao/.miniconda/envs/iopt/lib/python3.8/site-packages/seqio/dataset_providers.py", line 1041, in get_dataset
ds = source.get_dataset(split=split, shuffle=shuffle, seed=seed)
File "/data/users/zhouzhanchao/.miniconda/envs/iopt/lib/python3.8/site-packages/seqio/dataset_providers.py", line 371, in get_dataset
return self.tfds_dataset.load(
File "/data/users/zhouzhanchao/.miniconda/envs/iopt/lib/python3.8/site-packages/seqio/utils.py", line 137, in load
read_config=tfds.ReadConfig(
File "/data/users/zhouzhanchao/.miniconda/envs/iopt/lib/python3.8/site-packages/tensorflow_datasets/core/utils/read_config.py", line 112, in init
super(ReadConfig, self).init(**kwargs)
TypeError: init() got an unexpected keyword argument 'skip_prefetch'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "prepare_datasets.py", line 60, in
p.map(prepare_task,all_tasks)
File "/data/users/zhouzhanchao/.miniconda/envs/iopt/lib/python3.8/multiprocessing/pool.py", line 364, in map
return self._map_async(func, iterable, mapstar, chunksize).get()
File "/data/users/zhouzhanchao/.miniconda/envs/iopt/lib/python3.8/multiprocessing/pool.py", line 771, in get
raise self._value
TypeError: init() got an unexpected keyword argument 'skip_prefetch'`
Please can you tell me my problem and how to fix it?

**Comment by ontocord** [comment]
Did you figure this out?

**Comment by ontocord** [comment]
Is there an version of the flan dataset we can download?

**Comment by siyuyuan** [comment]
Hello, I saw the data set you compiled on huggingface. Has your data set added the maximum cap?

**Pull request closed without merging**
